### ISSUE TITLE
TypeError: fsuipc.FSUIPC is not a constructor

### ISSUE THREAD

**Issue by hiaaryan** [koesie10/fsuipc-node#11]
Hello, I've been getting this error when running in dev mode with electron. Am I doing something wrong?

This is inside a function.

![image](https://user-images.githubusercontent.com/30364412/120143385-abe91d00-c1fd-11eb-905b-e5bd980c5742.png)

**Comment by koesie10** [comment]
Could you prease try logging the complete `fsuipc` object to see what members it has? It could also be that the module is not compiled for your version of Electron, but for the version of Node you are running. I believe [this page](https://www.electronjs.org/docs/tutorial/using-native-node-modules) should help you in compiling the module.

**Comment by hiaaryan** [comment]
I rebuilt it using electron-rebuild and now I am able to log `fsuipc` and here is the object returned, however, the error persists. Pardon me, but I was not able to debug it through the object 😅

![image](https://user-images.githubusercontent.com/30364412/120155964-0fc81180-c20f-11eb-994c-4814109e965d.png)

**Comment by hiaaryan** [comment]
I am actually starting from scratch with an electron forge application. I'll let you know if I have the same error.

**Comment by hiaaryan** [comment]
Update: It has worked for me, with a new fresh install. So no problems for me now. Thanks for working on this :)
