### ISSUE TITLE
What is name and offset?

### ISSUE THREAD

**Issue by Triplecorpse** [koesie10/fsuipc-node#13]
![image](https://user-images.githubusercontent.com/11461770/134805838-4f96f2b8-ec39-46fd-8b57-d32aca66d601.png)
Could you please create a documentation on what features can be used?

**Comment by koesie10** [comment]
The name can be any name you want. Offsets can be found in the [FSUIPC SDK](https://fsuipc.simflight.com/beta/FSUIPC_SDK.zip) and in FSInterrogate, included as part of the FSUIPC SDK.
