### ISSUE TITLE
Not able to open connection on P3d

### ISSUE THREAD

**Issue by mberry73** [koesie10/fsuipc-node#14]
Hi

I'm trying to open a connection to my FSUIPC version 6 on P3D Version 5.

If I try to open the boilerplate code, without any argument I just get an error "undefined" back.
If I use Simulator.P3D however, I get 
"[FSUIPCError: Sim is not version requested] { code: 8 }"

The sim is running and FSUIPC up.

Is there any way to debug this issue? 
Any pointers would be appreciated :-)

**Comment by mberry73** [comment]
Sorry for the noise. that seems to have been my issue. Still don't know what exactly happened but it works now.

**Comment by koesie10** [comment]
Great, if you run into this problem again you can re-open this issue, since there's not really enough information to debug further.
