### ISSUE TITLE
Node-API

### ISSUE THREAD

**Issue by westlakem** [koesie10/fsuipc-node#17]
Any thoughts of converting this over to N-API?  The build is broken on Node 16, and Node 18 will be releasing soon

**Comment by carl0shd** [comment]
Hi @westlakem, maybe you need to compile the fsuipc artifact with node 16+ to work. I created a library to unify the community fsuipc work on https://github.com/tcavenezuela/fsuipc.js and is working just fine with node 16.4.2, take a look.

**Comment by westlakem** [comment]
So I took a look at this and it appears it's a problem with NAN on election, and not node 16.  I've opened up an issue on the NAN repo, however it appears the NAN project has received minimal support with forums saying to use node API instead.

**Comment by koesie10** [comment]
I've created a PR to convert this library to using Node API: #18. Would you be able to check whether it compiles and works for you in Electron?
