### ISSUE TITLE
Polling Strategy

### ISSUE THREAD

**Issue by chrismbeckett** [koesie10/fsuipc-node#2]
Do you recommend opening a connection, processing data multiple times (e.g. on a timer) and then closing the connection, or opening a connection, processing data, and closing every time you need data?

**Comment by koesie10** [comment]
I would recommend opening the connection only once. A connection is reusable and it is probably more stable to only open it once. When you call `process` and there is no FS instance open anymore, an error would be returned.

**Comment by chrismbeckett** [comment]
Awesome, thank you for the reply.
