### ISSUE TITLE
Xpuipc compatibility? 

### ISSUE THREAD

**Issue by victorgomez09** [koesie10/fsuipc-node#26]
I understand that it works the same as FSUIPC

**Comment by koesie10** [comment]
XPUIPC should be compatible with this module since it does use the same protocol as FSUIPC. However, you may need to run your Node script as administrator since XPUIPC tends to create Windows pipes which can only be accessed by administrators.

**Comment by Ben-LucaKoerber** [comment]
Unfortunately i get the following error message when trying to connect to xuipc 0.1.3:
"Incorrect version of FSUIPC, or not FSUIPC"
