### ISSUE TITLE
Latitude and Longitude - incorrect values?

### ISSUE THREAD

**Issue by chrismbeckett** [koesie10/fsuipc-node#3]
Using this library so far I have been able to access everything in FSUIPC that I need, but having a problem with latitude and longitude.

```
    fsObj.add('position_latitude', 0x0560, fsuipc.Type.Double);
    fsObj.add('position_longitude', 0x0568, fsuipc.Type.Double);
    const raw = await fsObj.process();

    const rawlat = raw['position_latitude'];
    const rawlong = raw['position_longitude'];
    const lat = (rawlat * 90.0) / (10001750.0 * 65536.0 * 65536.0);
    const long = (rawlong * 360.0) / (65535.0 * 65536.0 * 65536.0 * 65536.0);

    console.log(rawlat, rawlong, lat, long);
```
Output = 7.365159615089782e-308 -1.6738959397570212e+43 1.53e-322 -3.266764752792889e+26

I am also using a monitoring tool from RusCool to help learn all the FSUIPC data refs. When I use their tool and the same calculation I am using above, they get the right values.

![fsuipc_in](https://user-images.githubusercontent.com/6036093/50381520-26c9a900-063e-11e9-9976-7e0f82ee6894.JPG)
![fsuipc_out](https://user-images.githubusercontent.com/6036093/50381521-26c9a900-063e-11e9-95d6-7fee3e859bd6.JPG)

Is this related to a JavaScript issue with 64-bit floating point numbers? Have you been able to use this number to get Lat/Long? Please share you code if you have this working.

**Comment by koesie10** [comment]
The data type for latitude and longitude is a Long, so you'll need to use the `Int64` type to get back the correct values.

I have the following code for adding it to the `FSUIPC` object:

```
this.fsuipc.add("latitude", 0x0560, Type.Int64); // -ve for South, +ve for North. | #*90/(10001750*65536*65536)
this.fsuipc.add("longitude", 0x0568, Type.Int64); // -ve for West, +ve for East. | #*360/(65536*65536*65536*65536))
```

I have the following code in my class for converting it to decimal using decimal.js:

```
    get latitude(): number {
        return new Decimal(this.data.latitude).mul(new Decimal(90)).dividedBy(new Decimal("4.2957189152768E+16")).toNumber();
    }

    get longitude(): number {
        return new Decimal(this.data.longitude).mul(new Decimal(360)).dividedBy(new Decimal("1.84467440737096E+19")).toNumber();
    }
```

**Comment by chrismbeckett** [comment]
Switching from Double to Int64 fixed it (and a few other offsets where I had the wrong data type). Thanks very much for the code sample; and thanks very much for developing this library - makes it very easy to talk to flight simulators and is really helping me out.
