### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by melliiii** [koesie10/fsuipc-node#6]
Hei, i dont know if anyone will read this, but ill give this a try. 

If get those errors after i boot up my electron app:
```
ERROR in ./node_modules/bindings/bindings.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\Melli\github\RapsAcars_5\node_modules\bindings'

ERROR in ./node_modules/bindings/bindings.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Melli\github\RapsAcars_5\node_modules\bindings'

ERROR in ./node_modules/file-uri-to-path/index.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Melli\github\RapsAcars_5\node_modules\file-uri-to-path'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
```

I know it definitely has to do with fsuipc, so i wonder what it could be :c

I tried installing those packages and also included 
```
"browser": {
    "fs": false,
    "path": false
  },
```
in my package.json. Also I tried deleting node_modules and reinstall, but it still doesnt work :c

Im on Node v14.15.4 and npm v6.14.10, also using this electron-angular preset: https://github.com/maximegris/angular-electron

Help would be greatly appreciated :)

**Comment by m4xk0m** [comment]
Hi melliiii,

i do have the same issue currently i do not actively develop on this project, but i can remember got this issues too.  I think it has something to do with the sdk.  If i rembeer correctly its an c based / compiled module and if you dont use the correct compile it will not work :/

**Comment by koesie10** [comment]
If you are using Electron, this is probably because you are trying to run the fsuipc module inside your renderer process. You need to run it inside your main process, since it's a native module that depends on Node.js being available.
