### ISSUE TITLE
Compiled with a different version of Node.js

### ISSUE THREAD

**Issue by pTinosq** [koesie10/fsuipc-node#9]
Every time I run:
`const fsuipc = require('fsuipc');`

I get the following error:
```
Uncaught Error: The module 'REDACTED\node_modules\fsuipc\build\Release\fsuipc.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 89. Please try re-compiling or re-installing
```

Not sure if this is an issue on my end or if you need to just upgrade to newest nodejs version

**Comment by koesie10** [comment]
The module is not distributed as a compiled binary, so it's compiled on your machine. This probably means you updated your version of Node.js and it hasn't automatically rebuild the module. I know that when I'm doing development on the package locally I can use [the `install` script](https://github.com/koesie10/fsuipc-node/blob/master/package.json#L27) that is set on this package, but that won't work on installed packages. Can you try running [`npm rebuild`](https://docs.npmjs.com/cli/v7/commands/npm-rebuild) or [`yarn rebuild`](https://yarnpkg.com/cli/rebuild) (depending on which one you use)? That should rebuild the binary with your current Node version.

**Comment by pTinosq** [comment]
I ran `npm rebuild` and this was the output (I purged any lines that didn't include FSUIPC or similar)

It didn't fix the issue unfortunately :/

```
C:\REDACTED>npm rebuild

> fsuipc@0.4.1 installC:\REDACTED\node_modules\fsuipc
> node-gyp rebuild


C:\REDACTED\node_modules\fsuipc>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  index.cc
  FSUIPC.cc
  IPCUser.cc
  win_delay_load_hook.cc
     Creating library C:\REDACTED\node_modules\fsuipc\build\Release\fsuipc.lib
  and object C:\REDACTED\node_modules\fsuipc\build\Release\fsuipc.exp
  fsuipc.vcxproj -> C:\REDACTED\node_modules\fsuipc\build\Release\\fsuipc.node

[some other modules did their thing]

fsuipc@0.4.1 C:\REDACTED\node_modules\fsuipc

[more huge block of text about other modules]
```

Note that `C:\REDACTED` is just to protect project confidentiality it's more similar to
C:\Users\me\Desktop\project-name\

**Comment by pTinosq** [comment]
So I did a bit of reading and found this [Reddit post](https://www.reddit.com/r/node/comments/9yka5a/how_to_fix_module_compiled_in_a_different_version/) where the author states that his issue was:

"[His]  Electron app is Node v10.2.0, while [he's] been compiling font-manager this whole time with node v8.9.4. Think [he] just [has] to upgrade node in the directory and it should work..."

I investigated if this could be the same issue I'm having and I think it _might_ be.

When running `node -v` I get `v14.17.0` however when running `process.versions` it returns:
```js
ares: "1.16.1"
brotli: "1.0.9"
chrome: "91.0.4472.69"
electron: "13.0.1"
icu: "68.1"
llhttp: "2.1.3"
modules: "89"
napi: "7"
nghttp2: "1.41.0"
node: "14.16.0"
openssl: "1.1.1"
unicode: "13.0"
uv: "1.40.0"
v8: "9.1.269.28-electron.0"
zlib: "1.2.11"
```

Emphasis on the `node: "14.16.0"`

Now I'm not sure if a simple .16 -> .17 will be causing this issue but it might be a lead.

**Comment by pTinosq** [comment]
I fixed it by literally copy-pasting whatever I found on the internet that looked like it could solve my problem.

I basically just ran:
npm i -D electron-rebuild
npm i 

and then it just worked  - the wonders of programming.
